version: "3.3"
services:
  exactbank-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    environment:
      - SPRING_PROFILES_ACTIVE=test
    networks:
      - maianet
    depends_on:
      - pg-db
      - kafka

  pg-db:
    container_name: pg-db
    image: postgres:14.12-alpine3.18
    networks:
      - maianet
    environment:
      - POSTGRES_USER=maia
      - POSTGRES_PASSWORD=maiapw
      - POSTGRES_DB=transactions
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - maianet
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    networks:
      - maianet
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    networks:
      - maianet
    depends_on:
      - kafka
    ports:
      - "19000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:9092

  maiabank-api:
    container_name: maiabank-api
    image: dowglasmaia/maiabank
    networks:
      - maianet
    ports:
      - "8089:8089"

networks:
  maianet:
    driver: bridge

volumes:
  postgresql:
  postgresql_data:
  prometheus_data: